/**
 * Full UI copy for display languages Iban, Melanau, Bidayuh, and Kelabit.
 * Same key tree as `ms.translation` so no English fallbacks appear. Wording is
 * best-effort Sarawak-oriented; a fluent speaker should review for production.
 */
export const IBAN_DISPLAY = {
  common: {
    language: "Jaku Iban",
    phoneAutoConnect: "Auto sambung telefon",
    customization: "Ngerunding",
    changeFontSize: "Ubah besai hurup",
    changeThemeColour: "Ubah warna tema",
    linked: "Nyaut: {{name}}",
    unpaired: "Enda nyaut · scan QR",
    unlinkPhone: "Putus paut",
    themeLight: "Cahaya",
    themeDark: "Gelap",
    themePurple: "Ungu",
    close: "Tutup",
    search: "Miga",
    selectDisplayLanguage: "Pilih jaku papar",
    home: "Rumah",
    sidebarItemTitle: "{{label}} — {{hint}}",
    doubleTapHome: "Dwiketik ikon ke rumah",
    unitKm: "km",
  },
  sidebar: {
    settings: "Pemetting",
    map: "Peta",
    voice: "Suara",
    bluetooth: "Bluetooth",
    car: "Kerita",
  },
  topbar: {
    searchLocked: "Miga dikunci lebuh undur",
    searchBar: "Bar miga",
    gearShortcutTip: "Petua: Ctrl+Alt+P / Ctrl+Alt+R / Ctrl+Alt+N / Ctrl+Alt+D nanggau gear",
  },
  map: {
    enterDestination: "Masuk destinasi",
    routingTo: "Jalai ngagai: {{destination}}",
    nearbyStations: "Stesen ngecas ke deka",
    navigateToStation: "Bekunsi ngagai {{station}}",
    endNavigation: "Mungkal bekunsi",
    navigation: "Bekunsi",
    tapToEnlarge: "Sentuh kena besarka",
    openFullMap: "Buka peta bekunsi penuh",
    searchDestination: "Miga destinasi",
    geoUnavailable:
      "GPS enda uli. Lalau ngena lokasi demo nyentokka kebenaran lokasi diberi.",
    homeShortcut: "Rumah",
    navigateHome: "Bekunsi ngagai rumah",
    errors: {
      waitingGps: "Ngadang lokasi GPS…",
      destinationNotFound: "Destinasi enda uli dipeda.",
      routeNotAvailable: "Jalai enda uli.",
      routingFailed: "Jalai enda mujur.",
    },
  },
  voice: {
    listening: "Mendinga…",
    sayCommand: "Jaku arahan…",
    notSupported: "Pengecaman suara enda disokong ba browser tu.",
    tapToStart: "Sentuh deka mula mendinga",
  },
  car: {
    drivingModes: "Mod nunda kerita",
    adaptiveCruise: "Kawal jelajah adaptif",
    autoParking: "Parkir automatik",
    laneCentering: "Pusat lorong",
  },
  gear: {
    lowBeam: "Lampu baruh",
    highBeam: "Lampu tinggi",
    flashlightLow: "Senter baruh",
    flashlightHigh: "Senter tinggi",
    doors: "Pintu",
    doorOpenTitle: "Pintu tebuka - klik deka nutup",
    doorClosedTitle: "Pintu nutup - klik deka buka simulasi",
    previousGear: "Gear ke diatu",
    nextGear: "Gear ke tu",
    kmh: "KM/J",
    useCtrlShortcut: "Guna Ctrl+Alt+P/R/N/D nanggau gear",
  },
  search: {
    voiceSearch: "Miga suara",
    stop: "Stop",
    quickAutoParking: "Parkir automatik",
    quickPhoneConnect: "Auto sambung telefon",
    quickAdaptiveCruise: "Jelajah adaptif",
    quickLaneCentering: "Pusat lorong",
    quickNavigation: "Bekunsi",
  },
  bluetooth: {
    title: "Bluetooth",
    deviceName: "Nama peranti",
    pairedDevice: "Peranti nyaut",
    availableDevices: "Peranti bisi",
    unpairedShort: "Enda nyaut · nadai peranti",
    unpair: "Putus paut",
  },
  brightness: {
    auto: "Auto",
    manual: "Manual",
    decrease: "Kurang penerang",
    increase: "Tambah penerang",
    toggle: "Tuka auto/manual penerang",
    autoToManual: "Auto - sentuh ke Manual",
    manualToAuto: "Manual - sentuh ke Auto",
  },
  climate: {
    decrease: "Kurang suhu",
    increase: "Tambah suhu",
    ac: "A/C",
    ventDown: "Aliran baruh",
    ventMiddle: "Aliran tengah",
    ventUp: "Aliran atas",
  },
  status: {
    nearbyCharging: "STESEN NGECAS KE DEKA",
    left: "Aki",
    traveled: "Jalai udah",
    back: "Muli",
  },
  weather: {
    sunny: "Cerah",
    cloudy: "Berawan",
    rainy: "Hujan",
    snowy: "Salji",
    stormy: "Ribut",
  },
  traffic: {
    tooClose: "KLIP DEKAT - JAGA JARAK",
    warning: "AMARAN",
    closeWarning: "Kecilka jaka",
    live: "LANGSUNG",
    view360: "Papar 360°",
    fullscreenHint: "Trafik pintar - seret deka meda ngelingi (360°)",
  },
  notFound: {
    title: "Laman enda uli dipeda",
    goHome: "Muli",
  },
  reverse: {
    topView: "PANDANGAN ATAS",
    reverseCam: "KAMERA UNDUR",
    cameraUnavailable: "Kamera enda uli",
    allowCamera: "Benar akses kamera ke papar undur",
  },
  pair: {
    phoneLinked: "Telefon nyaut!",
    pairedAs: "Peranti nuan nyaut nyadi:",
    backToSettings: "Muli ke pemetting",
  },
  media: {
    progress: "Kemaju",
    repeatOne: "Ulang trek diatu",
    previousTrack: "Trek ke diatu",
    playPause: "Main tauka jeda",
    nextTrack: "Trek ke tu",
    shuffle: "Main rawak",
    volume: "Kelantangan",
    collapse: "Runtuhka panel muzik",
    expandPanel: "Kembarka panel muzik",
  },
  leaflet: {
    zoomIn: "Zum masuk",
    zoomOut: "Zum keluar",
  },
  nearby: {
    refresh: "Muat baru",
    closePanel: "Tutup",
  },
  settings: {
    userManualTitle: "Manual penguna",
    userManualTeaser:
      "Sentuh deka buka manual penuh. Ngelambar susun atur dashboard, media, penerang, bekunsi, enggau paut telefon.",
    userManualHint:
      "Sentuh kad muzik deka buka senarai main. Guna Ctrl+Alt+P / Ctrl+Alt+R / Ctrl+Alt+N / Ctrl+Alt+D nanggau gear, enggau set penerang Auto tauka Manual ditu.",
    userManualChrome: "Buka laman tu dalam Chrome ke sokongan pintasan enggau penerang ti manah.",
    manual: {
      home: {
        title: "Dashboard rumah",
        points: [
          "Kolum kiri mandang trafik tauka media nitihka skrin.",
          "Kolum tengah mandang peta enggau kawal penerang.",
          "Kolum kanan mandang gear, bateri, enggau cuaca.",
        ],
      },
      media: {
        title: "Media enggau muzik",
        points: [
          "Sentuh kad muzik deka kembarka pemain enggau kawal main.",
          "Guna main/jeda enggau langkau deka nanggau trek.",
          "Papan kekunci: Ctrl+Alt+P / Ctrl+Alt+R / Ctrl+Alt+N / Ctrl+Alt+D nanggau gear lebuh nunda.",
          "Buka laman tu dalam Chrome ke sokongan pintasan enggau penerang ti manah.",
          "Kad muzik padat sejajar enggau kad bukai ba baris baruh.",
        ],
      },
      brightness: {
        title: "Penerang enggau iklim",
        points: [
          "Mod auto ngesuaika penerang lebuh data skrin uli.",
          "Lalu skrin malap, mod auto uli nanganka papar.",
          "Mod manual nguji ngesuaika penerang enggau butang +/−.",
          "Kad baruh mengkang sejajar ke susun atur konsisten.",
        ],
      },
      navigation: {
        title: "Bekunsi enggau peta",
        points: [
          "Ba skrin peta, guna bar miga deka set destinasi.",
          "Sentuh stesen ke deka tauka amaran trafik ke konteks jalai.",
          "Peta sejajar enggau panel gear ba baris atas.",
        ],
      },
      phone: {
        title: "Paut telefon enggau pemetting",
        points: [
          "Imbas kod QR deka paut telefon automatik.",
          "Ubah jaku papar, tema, enggau besai fon ba panel tu.",
          "Guna menua tu deka meresa kawal enggau ngemisi pemilih.",
        ],
      },
    },
  },
} as const;

export const MELANAU_DISPLAY = {
  common: {
    language: "Jaku Melanau",
    phoneAutoConnect: "Sambung telefon otomatis",
    customization: "Penyesuaian",
    changeFontSize: "Ubah saiz fon",
    changeThemeColour: "Ubah warna tema",
    linked: "Terhubung: {{name}}",
    unpaired: "Belum terhubung · imbas QR",
    unlinkPhone: "Putus sambungan",
    themeLight: "Cahaya",
    themeDark: "Gelap",
    themePurple: "Ungu",
    close: "Tutup",
    search: "Cari",
    selectDisplayLanguage: "Pilih jaku paparan",
    home: "Lumah",
    sidebarItemTitle: "{{label}} — {{hint}}",
    doubleTapHome: "Dwiketik ikon ke lumah",
    unitKm: "km",
  },
  sidebar: {
    settings: "Tetapan",
    map: "Peta",
    voice: "Suara",
    bluetooth: "Bluetooth",
    car: "Kerita",
  },
  topbar: {
    searchLocked: "Carian dikunci lebuh undur",
    searchBar: "Bar carian",
    gearShortcutTip: "Petua: Ctrl+Alt+P / Ctrl+Alt+R / Ctrl+Alt+N / Ctrl+Alt+D nanggau gear",
  },
  map: {
    enterDestination: "Masuk destinasi",
    routingTo: "Laluan ngagai: {{destination}}",
    nearbyStations: "Stesen ngecas ke dekat",
    navigateToStation: "Navigasi ngagai {{station}}",
    endNavigation: "Mungkal navigasi",
    navigation: "Navigasi",
    tapToEnlarge: "Sentuh ke besarkan",
    openFullMap: "Buka peta navigasi penuh",
    searchDestination: "Cari destinasi",
    geoUnavailable:
      "GPS enda uli. Laluan ngena lokasi demo nyentokka kebenaran lokasi diberi.",
    homeShortcut: "Lumah",
    navigateHome: "Navigasi ngagai lumah",
    errors: {
      waitingGps: "Ngadang lokasi GPS…",
      destinationNotFound: "Destinasi enda uli dipeda.",
      routeNotAvailable: "Laluan enda uli.",
      routingFailed: "Laluan gagal.",
    },
  },
  voice: {
    listening: "Mendinga…",
    sayCommand: "Sebut arahan…",
    notSupported: "Pengecaman suara enda disokong ba browser tu.",
    tapToStart: "Sentuh ke mula mendinga",
  },
  car: {
    drivingModes: "Mod nunda",
    adaptiveCruise: "Kawalan jelajah adaptif",
    autoParking: "Parkir automatik",
    laneCentering: "Pusat lorong",
  },
  gear: {
    lowBeam: "Lampu baruh",
    highBeam: "Lampu tinggi",
    flashlightLow: "Senter baruh",
    flashlightHigh: "Senter tinggi",
    doors: "Pintu",
    doorOpenTitle: "Pintu tebuka - klik ke tutup",
    doorClosedTitle: "Pintu nutup - klik ke buka simulasi",
    previousGear: "Gear ke lepas",
    nextGear: "Gear ke duri",
    kmh: "KM/J",
    useCtrlShortcut: "Guna Ctrl+Alt+P/R/N/D nanggau gear",
  },
  search: {
    voiceSearch: "Carian suara",
    stop: "Stop",
    quickAutoParking: "Parkir automatik",
    quickPhoneConnect: "Sambung automatik telefon",
    quickAdaptiveCruise: "Jelajah adaptif",
    quickLaneCentering: "Pusat lorong",
    quickNavigation: "Navigasi",
  },
  bluetooth: {
    title: "Bluetooth",
    deviceName: "Nama peranti",
    pairedDevice: "Peranti terhubung",
    availableDevices: "Peranti bisi",
    unpairedShort: "Belum terhubung · nadai peranti",
    unpair: "Putus paut",
  },
  brightness: {
    auto: "Auto",
    manual: "Manual",
    decrease: "Kurang penerang",
    increase: "Tambah penerang",
    toggle: "Tuka auto/manual penerang",
    autoToManual: "Auto - sentuh ke Manual",
    manualToAuto: "Manual - sentuh ke Auto",
  },
  climate: {
    decrease: "Kurang suhu",
    increase: "Tambah suhu",
    ac: "A/C",
    ventDown: "Aliran baruh",
    ventMiddle: "Aliran tengah",
    ventUp: "Aliran atas",
  },
  status: {
    nearbyCharging: "STESEN NGECAS KE DEKAT",
    left: "Aki",
    traveled: "Jalai",
    back: "Muli",
  },
  weather: {
    sunny: "Cerah",
    cloudy: "Berawan",
    rainy: "Hujan",
    snowy: "Salji",
    stormy: "Ribut",
  },
  traffic: {
    tooClose: "KLIP DEKAT - JAGA JARAK",
    warning: "AMARAN",
    closeWarning: "Kecilka amaran",
    live: "LANGSUNG",
    view360: "Paparan 360°",
    fullscreenHint: "Trafik pintar - seret ke meda ngelingi (360°)",
  },
  notFound: {
    title: "Laman enda uli dipeda",
    goHome: "Muli",
  },
  reverse: {
    topView: "PANDANGAN ATAS",
    reverseCam: "KAMERA UNDUR",
    cameraUnavailable: "Kamera enda uli",
    allowCamera: "Benar akses kamera ke papar undur",
  },
  pair: {
    phoneLinked: "Telefon terhubung!",
    pairedAs: "Peranti nuan terhubung nyadi:",
    backToSettings: "Muli ke tetapan",
  },
  media: {
    progress: "Kemaju",
    repeatOne: "Ulang trek diatu",
    previousTrack: "Trek ke lepas",
    playPause: "Main tauka jeda",
    nextTrack: "Trek ke duri",
    shuffle: "Main rawak",
    volume: "Kelantangan",
    collapse: "Runtuhka panel muzik",
    expandPanel: "Kembarka panel muzik",
  },
  leaflet: {
    zoomIn: "Zum masuk",
    zoomOut: "Zum keluar",
  },
  nearby: {
    refresh: "Muat baru",
    closePanel: "Tutup",
  },
  settings: {
    userManualTitle: "Manual penguna",
    userManualTeaser:
      "Sentuh ke buka manual penuh. Ngelambar dashboard, media, penerang, navigasi, enggau paut telefon.",
    userManualHint:
      "Sentuh kad muzik ke buka senarai main. Guna Ctrl+Alt+P / Ctrl+Alt+R / Ctrl+Alt+N / Ctrl+Alt+D nanggau gear, enggau set penerang Auto tauka Manual ditu.",
    userManualChrome: "Buka laman tu dalam Chrome ke sokongan pintasan enggau penerang ti manah.",
    manual: {
      home: {
        title: "Dashboard lumah",
        points: [
          "Kolum kiri mandang trafik tauka media nitihka skrin.",
          "Kolum tengah mandang peta enggau kawal penerang.",
          "Kolum kanan mandang gear, bateri, enggau cuaca.",
        ],
      },
      media: {
        title: "Media enggau muzik",
        points: [
          "Sentuh kad muzik ke kembarka pemain enggau kawal main.",
          "Guna main/jeda enggau langkau ke nanggau trek.",
          "Papan kekunci: Ctrl+Alt+P / Ctrl+Alt+R / Ctrl+Alt+N / Ctrl+Alt+D nanggau gear lebuh nunda.",
          "Buka laman tu dalam Chrome ke sokongan pintasan enggau penerang ti manah.",
          "Kad muzik padat sejajar enggau kad bukai ba baris baruh.",
        ],
      },
      brightness: {
        title: "Penerang enggau iklim",
        points: [
          "Mod auto ngesuaika penerang lebuh data skrin uli.",
          "Lalu skrin malap, mod auto uli nanganka papar.",
          "Mod manual nguji ngesuaika penerang enggau butang +/−.",
          "Kad baruh mengkang sejajar ke susun atur konsisten.",
        ],
      },
      navigation: {
        title: "Navigasi enggau peta",
        points: [
          "Ba skrin peta, guna bar carian ke set destinasi.",
          "Sentuh stesen ke dekat tauka amaran trafik ke konteks laluan.",
          "Peta sejajar enggau panel gear ba baris atas.",
        ],
      },
      phone: {
        title: "Paut telefon enggau tetapan",
        points: [
          "Imbas kod QR ke paut telefon automatik.",
          "Ubah jaku paparan, tema, enggau saiz fon ba panel tu.",
          "Guna menua tu ke meresa kawal enggau ngemisi pemilih.",
        ],
      },
    },
  },
} as const;

export const BIDAYUH_DISPLAY = {
  common: {
    language: "Jaku Bidayuh",
    phoneAutoConnect: "Sambung telefon otomatis",
    customization: "Penyesuaian",
    changeFontSize: "Ubah saiz fon",
    changeThemeColour: "Ubah warna tema",
    linked: "Nyambung: {{name}}",
    unpaired: "Enda nyambung · imbas QR",
    unlinkPhone: "Putus sambungan",
    themeLight: "Cahaya",
    themeDark: "Gelap",
    themePurple: "Ungu",
    close: "Tutup",
    search: "Cari",
    selectDisplayLanguage: "Pilih jaku papar",
    home: "Lamin",
    sidebarItemTitle: "{{label}} — {{hint}}",
    doubleTapHome: "Dwiketik ikon ke lamin",
    unitKm: "km",
  },
  sidebar: {
    settings: "Tetapan",
    map: "Peta",
    voice: "Suara",
    bluetooth: "Bluetooth",
    car: "Kerita",
  },
  topbar: {
    searchLocked: "Carian dikunci lebuh undur",
    searchBar: "Bar carian",
    gearShortcutTip: "Petua: Ctrl+Alt+P / Ctrl+Alt+R / Ctrl+Alt+N / Ctrl+Alt+D nanggau gear",
  },
  map: {
    enterDestination: "Masuk destinasi",
    routingTo: "Laluan ngagai: {{destination}}",
    nearbyStations: "Stesen ngecas ke dekat",
    navigateToStation: "Navigasi ngagai {{station}}",
    endNavigation: "Mungkal navigasi",
    navigation: "Navigasi",
    tapToEnlarge: "Sentuh ke besarkan",
    openFullMap: "Buka peta navigasi penuh",
    searchDestination: "Cari destinasi",
    geoUnavailable:
      "GPS enda uli. Laluan ngena lokasi demo nyentokka kebenaran lokasi diberi.",
    homeShortcut: "Lamin",
    navigateHome: "Navigasi ngagai lamin",
    errors: {
      waitingGps: "Ngadang lokasi GPS…",
      destinationNotFound: "Destinasi enda uli dipeda.",
      routeNotAvailable: "Laluan enda uli.",
      routingFailed: "Laluan gagal.",
    },
  },
  voice: {
    listening: "Mendinga…",
    sayCommand: "Sebut arahan…",
    notSupported: "Pengecaman suara enda disokong ba browser tu.",
    tapToStart: "Sentuh ke mula mendinga",
  },
  car: {
    drivingModes: "Mod nunda",
    adaptiveCruise: "Kawalan jelajah adaptif",
    autoParking: "Parkir automatik",
    laneCentering: "Pusat lorong",
  },
  gear: {
    lowBeam: "Lampu baruh",
    highBeam: "Lampu tinggi",
    flashlightLow: "Senter baruh",
    flashlightHigh: "Senter tinggi",
    doors: "Pintu",
    doorOpenTitle: "Pintu tebuka - klik ke tutup",
    doorClosedTitle: "Pintu nutup - klik ke buka simulasi",
    previousGear: "Gear ke lepas",
    nextGear: "Gear ke duri",
    kmh: "KM/J",
    useCtrlShortcut: "Guna Ctrl+Alt+P/R/N/D nanggau gear",
  },
  search: {
    voiceSearch: "Carian suara",
    stop: "Stop",
    quickAutoParking: "Parkir automatik",
    quickPhoneConnect: "Sambung automatik telefon",
    quickAdaptiveCruise: "Jelajah adaptif",
    quickLaneCentering: "Pusat lorong",
    quickNavigation: "Navigasi",
  },
  bluetooth: {
    title: "Bluetooth",
    deviceName: "Nama peranti",
    pairedDevice: "Peranti nyambung",
    availableDevices: "Peranti bisi",
    unpairedShort: "Enda nyambung · nadai peranti",
    unpair: "Putus paut",
  },
  brightness: {
    auto: "Auto",
    manual: "Manual",
    decrease: "Kurang penerang",
    increase: "Tambah penerang",
    toggle: "Tuka auto/manual penerang",
    autoToManual: "Auto - sentuh ke Manual",
    manualToAuto: "Manual - sentuh ke Auto",
  },
  climate: {
    decrease: "Kurang suhu",
    increase: "Tambah suhu",
    ac: "A/C",
    ventDown: "Aliran baruh",
    ventMiddle: "Aliran tengah",
    ventUp: "Aliran atas",
  },
  status: {
    nearbyCharging: "STESEN NGECAS KE DEKAT",
    left: "Aki",
    traveled: "Jalai",
    back: "Muli",
  },
  weather: {
    sunny: "Cerah",
    cloudy: "Berawan",
    rainy: "Hujan",
    snowy: "Salji",
    stormy: "Ribut",
  },
  traffic: {
    tooClose: "KLIP DEKAT - JAGA JARAK",
    warning: "AMARAN",
    closeWarning: "Kecilka amaran",
    live: "LANGSUNG",
    view360: "Paparan 360°",
    fullscreenHint: "Trafik pintar - seret ke meda ngelingi (360°)",
  },
  notFound: {
    title: "Laman enda uli dipeda",
    goHome: "Muli",
  },
  reverse: {
    topView: "PANDANGAN ATAS",
    reverseCam: "KAMERA UNDUR",
    cameraUnavailable: "Kamera enda uli",
    allowCamera: "Benar akses kamera ke papar undur",
  },
  pair: {
    phoneLinked: "Telefon nyambung!",
    pairedAs: "Peranti nuan nyambung nyadi:",
    backToSettings: "Muli ke tetapan",
  },
  media: {
    progress: "Kemaju",
    repeatOne: "Ulang trek diatu",
    previousTrack: "Trek ke lepas",
    playPause: "Main tauka jeda",
    nextTrack: "Trek ke duri",
    shuffle: "Main rawak",
    volume: "Kelantangan",
    collapse: "Runtuhka panel muzik",
    expandPanel: "Kembarka panel muzik",
  },
  leaflet: {
    zoomIn: "Zum masuk",
    zoomOut: "Zum keluar",
  },
  nearby: {
    refresh: "Muat baru",
    closePanel: "Tutup",
  },
  settings: {
    userManualTitle: "Manual penguna",
    userManualTeaser:
      "Sentuh ke buka manual penuh. Ngelambar dashboard, media, penerang, navigasi, enggau paut telefon.",
    userManualHint:
      "Sentuh kad muzik ke buka senarai main. Guna Ctrl+Alt+P / Ctrl+Alt+R / Ctrl+Alt+N / Ctrl+Alt+D nanggau gear, enggau set penerang Auto tauka Manual ditu.",
    userManualChrome: "Buka laman tu dalam Chrome ke sokongan pintasan enggau penerang ti manah.",
    manual: {
      home: {
        title: "Dashboard lamin",
        points: [
          "Kolum kiri mandang trafik tauka media nitihka skrin.",
          "Kolum tengah mandang peta enggau kawal penerang.",
          "Kolum kanan mandang gear, bateri, enggau cuaca.",
        ],
      },
      media: {
        title: "Media enggau muzik",
        points: [
          "Sentuh kad muzik ke kembarka pemain enggau kawal main.",
          "Guna main/jeda enggau langkau ke nanggau trek.",
          "Papan kekunci: Ctrl+Alt+P / Ctrl+Alt+R / Ctrl+Alt+N / Ctrl+Alt+D nanggau gear lebuh nunda.",
          "Buka laman tu dalam Chrome ke sokongan pintasan enggau penerang ti manah.",
          "Kad muzik padat sejajar enggau kad bukai ba baris baruh.",
        ],
      },
      brightness: {
        title: "Penerang enggau iklim",
        points: [
          "Mod auto ngesuaika penerang lebuh data skrin uli.",
          "Lalu skrin malap, mod auto uli nanganka papar.",
          "Mod manual nguji ngesuaika penerang enggau butang +/−.",
          "Kad baruh mengkang sejajar ke susun atur konsisten.",
        ],
      },
      navigation: {
        title: "Navigasi enggau peta",
        points: [
          "Ba skrin peta, guna bar carian ke set destinasi.",
          "Sentuh stesen ke dekat tauka amaran trafik ke konteks laluan.",
          "Peta sejajar enggau panel gear ba baris atas.",
        ],
      },
      phone: {
        title: "Paut telefon enggau tetapan",
        points: [
          "Imbas kod QR ke paut telefon automatik.",
          "Ubah jaku papar, tema, enggau saiz fon ba panel tu.",
          "Guna menua tu ke meresa kawal enggau ngemisi pemilih.",
        ],
      },
    },
  },
} as const;

export const KELABIT_DISPLAY = {
  common: {
    language: "Jaku Kelabit",
    phoneAutoConnect: "Sambung telefon otomatis",
    customization: "Penyesuaian",
    changeFontSize: "Ubah saiz fon",
    changeThemeColour: "Ubah warna tema",
    linked: "Nyaut: {{name}}",
    unpaired: "Enda nyaut · imbas QR",
    unlinkPhone: "Putus paut",
    themeLight: "Cahaya",
    themeDark: "Gelap",
    themePurple: "Ungu",
    close: "Tutup",
    search: "Cari",
    selectDisplayLanguage: "Pilih jaku papar",
    home: "Lamin",
    sidebarItemTitle: "{{label}} — {{hint}}",
    doubleTapHome: "Dwiketik ikon ke lamin",
    unitKm: "km",
  },
  sidebar: {
    settings: "Tetapan",
    map: "Peta",
    voice: "Suara",
    bluetooth: "Bluetooth",
    car: "Kerita",
  },
  topbar: {
    searchLocked: "Carian dikunci lebuh undur",
    searchBar: "Bar carian",
    gearShortcutTip: "Petua: Ctrl+Alt+P / Ctrl+Alt+R / Ctrl+Alt+N / Ctrl+Alt+D nanggau gear",
  },
  map: {
    enterDestination: "Masuk destinasi",
    routingTo: "Laluan ngagai: {{destination}}",
    nearbyStations: "Stesen ngecas ke dekat",
    navigateToStation: "Navigasi ngagai {{station}}",
    endNavigation: "Mungkal navigasi",
    navigation: "Navigasi",
    tapToEnlarge: "Sentuh ke besarkan",
    openFullMap: "Buka peta navigasi penuh",
    searchDestination: "Cari destinasi",
    geoUnavailable:
      "GPS enda uli. Laluan ngena lokasi demo nyentokka kebenaran lokasi diberi.",
    homeShortcut: "Lamin",
    navigateHome: "Navigasi ngagai lamin",
    errors: {
      waitingGps: "Ngadang lokasi GPS…",
      destinationNotFound: "Destinasi enda uli dipeda.",
      routeNotAvailable: "Laluan enda uli.",
      routingFailed: "Laluan gagal.",
    },
  },
  voice: {
    listening: "Mendinga…",
    sayCommand: "Sebut arahan…",
    notSupported: "Pengecaman suara enda disokong ba browser tu.",
    tapToStart: "Sentuh ke mula mendinga",
  },
  car: {
    drivingModes: "Mod nunda",
    adaptiveCruise: "Kawalan jelajah adaptif",
    autoParking: "Parkir automatik",
    laneCentering: "Pusat lorong",
  },
  gear: {
    lowBeam: "Lampu baruh",
    highBeam: "Lampu tinggi",
    flashlightLow: "Senter baruh",
    flashlightHigh: "Senter tinggi",
    doors: "Pintu",
    doorOpenTitle: "Pintu tebuka - klik ke tutup",
    doorClosedTitle: "Pintu nutup - klik ke buka simulasi",
    previousGear: "Gear ke lepas",
    nextGear: "Gear ke duri",
    kmh: "KM/J",
    useCtrlShortcut: "Guna Ctrl+Alt+P/R/N/D nanggau gear",
  },
  search: {
    voiceSearch: "Carian suara",
    stop: "Stop",
    quickAutoParking: "Parkir automatik",
    quickPhoneConnect: "Sambung automatik telefon",
    quickAdaptiveCruise: "Jelajah adaptif",
    quickLaneCentering: "Pusat lorong",
    quickNavigation: "Navigasi",
  },
  bluetooth: {
    title: "Bluetooth",
    deviceName: "Nama peranti",
    pairedDevice: "Peranti nyaut",
    availableDevices: "Peranti bisi",
    unpairedShort: "Enda nyaut · nadai peranti",
    unpair: "Putus paut",
  },
  brightness: {
    auto: "Auto",
    manual: "Manual",
    decrease: "Kurang penerang",
    increase: "Tambah penerang",
    toggle: "Tuka auto/manual penerang",
    autoToManual: "Auto - sentuh ke Manual",
    manualToAuto: "Manual - sentuh ke Auto",
  },
  climate: {
    decrease: "Kurang suhu",
    increase: "Tambah suhu",
    ac: "A/C",
    ventDown: "Aliran baruh",
    ventMiddle: "Aliran tengah",
    ventUp: "Aliran atas",
  },
  status: {
    nearbyCharging: "STESEN NGECAS KE DEKAT",
    left: "Aki",
    traveled: "Jalai",
    back: "Muli",
  },
  weather: {
    sunny: "Cerah",
    cloudy: "Berawan",
    rainy: "Hujan",
    snowy: "Salji",
    stormy: "Ribut",
  },
  traffic: {
    tooClose: "KLIP DEKAT - JAGA JARAK",
    warning: "AMARAN",
    closeWarning: "Kecilka amaran",
    live: "LANGSUNG",
    view360: "Paparan 360°",
    fullscreenHint: "Trafik pintar - seret ke meda ngelingi (360°)",
  },
  notFound: {
    title: "Laman enda uli dipeda",
    goHome: "Muli",
  },
  reverse: {
    topView: "PANDANGAN ATAS",
    reverseCam: "KAMERA UNDUR",
    cameraUnavailable: "Kamera enda uli",
    allowCamera: "Benar akses kamera ke papar undur",
  },
  pair: {
    phoneLinked: "Telefon nyaut!",
    pairedAs: "Peranti nuan nyaut nyadi:",
    backToSettings: "Muli ke tetapan",
  },
  media: {
    progress: "Kemaju",
    repeatOne: "Ulang trek diatu",
    previousTrack: "Trek ke lepas",
    playPause: "Main tauka jeda",
    nextTrack: "Trek ke duri",
    shuffle: "Main rawak",
    volume: "Kelantangan",
    collapse: "Runtuhka panel muzik",
    expandPanel: "Kembarka panel muzik",
  },
  leaflet: {
    zoomIn: "Zum masuk",
    zoomOut: "Zum keluar",
  },
  nearby: {
    refresh: "Muat baru",
    closePanel: "Tutup",
  },
  settings: {
    userManualTitle: "Manual penguna",
    userManualTeaser:
      "Sentuh ke buka manual penuh. Ngelambar dashboard, media, penerang, navigasi, enggau paut telefon.",
    userManualHint:
      "Sentuh kad muzik ke buka senarai main. Guna Ctrl+Alt+P / Ctrl+Alt+R / Ctrl+Alt+N / Ctrl+Alt+D nanggau gear, enggau set penerang Auto tauka Manual ditu.",
    userManualChrome: "Buka laman tu dalam Chrome ke sokongan pintasan enggau penerang ti manah.",
    manual: {
      home: {
        title: "Dashboard lamin",
        points: [
          "Kolum kiri mandang trafik tauka media nitihka skrin.",
          "Kolum tengah mandang peta enggau kawal penerang.",
          "Kolum kanan mandang gear, bateri, enggau cuaca.",
        ],
      },
      media: {
        title: "Media enggau muzik",
        points: [
          "Sentuh kad muzik ke kembarka pemain enggau kawal main.",
          "Guna main/jeda enggau langkau ke nanggau trek.",
          "Papan kekunci: Ctrl+Alt+P / Ctrl+Alt+R / Ctrl+Alt+N / Ctrl+Alt+D nanggau gear lebuh nunda.",
          "Buka laman tu dalam Chrome ke sokongan pintasan enggau penerang ti manah.",
          "Kad muzik padat sejajar enggau kad bukai ba baris baruh.",
        ],
      },
      brightness: {
        title: "Penerang enggau iklim",
        points: [
          "Mod auto ngesuaika penerang lebuh data skrin uli.",
          "Lalu skrin malap, mod auto uli nanganka papar.",
          "Mod manual nguji ngesuaika penerang enggau butang +/−.",
          "Kad baruh mengkang sejajar ke susun atur konsisten.",
        ],
      },
      navigation: {
        title: "Navigasi enggau peta",
        points: [
          "Ba skrin peta, guna bar carian ke set destinasi.",
          "Sentuh stesen ke dekat tauka amaran trafik ke konteks laluan.",
          "Peta sejajar enggau panel gear ba baris atas.",
        ],
      },
      phone: {
        title: "Paut telefon enggau tetapan",
        points: [
          "Imbas kod QR ke paut telefon automatik.",
          "Ubah jaku papar, tema, enggau saiz fon ba panel tu.",
          "Guna menua tu ke meresa kawal enggau ngemisi pemilih.",
        ],
      },
    },
  },
} as const;
